Parametrized topic and others. Removed module camel processor. To fix deserialization from protobuf.  error: java.lang.RuntimeException: Failed to deserialize Protobuf message 	at com.fx.market.kafka.FxRateEventProtoSerde$FxRateEventProtoDeserializer.deserialize(FxRateEventProtoSerde.java:33) ~[main/:na] 	at com.fx.market.kafka.FxRateEventProtoSerde$FxRateEventProtoDeserializer.deserialize(FxRateEventProtoSerde.java:27) ~[main/:na] 	at org.apache.kafka.common.serialization.Deserializer.deserialize(Deserializer.java:62) ~[kafka-clients-3.7.1.jar:na] 	at org.apache.kafka.streams.processor.internals.SourceNode.deserializeValue(SourceNode.java:58) ~[kafka-streams-3.7.1.jar:na] 	at org.apache.kafka.streams.processor.internals.RecordDeserializer.deserialize(RecordDeserializer.java:66) ~[kafka-streams-3.7.1.jar:na] 	at org.apache.kafka.streams.processor.internals.RecordQueue.updateHead(RecordQueue.java:204) ~[kafka-streams-3.7.1.jar:na] 	at org.apache.kafka.streams.processor.internals.RecordQueue.addRawRecords(RecordQueue.java:128) ~[kafka-streams-3.7.1.jar:na] 	at org.apache.kafka.streams.processor.internals.PartitionGroup.addRawRecords(PartitionGroup.java:285) ~[kafka-streams-3.7.1.jar:na] 	at org.apache.kafka.streams.processor.internals.StreamTask.addRecords(StreamTask.java:1039) ~[kafka-streams-3.7.1.jar:na] 	at org.apache.kafka.streams.processor.internals.TaskManager.addRecordsToTasks(TaskManager.java:1782) ~[kafka-streams-3.7.1.jar:na] 	at org.apache.kafka.streams.processor.internals.StreamThread.pollPhase(StreamThread.java:1208) ~[kafka-streams-3.7.1.jar:na] 	at org.apache.kafka.streams.processor.internals.StreamThread.runOnceWithoutProcessingThreads(StreamThread.java:909) ~[kafka-streams-3.7.1.jar:na] 	at org.apache.kafka.streams.processor.internals.StreamThread.runLoop(StreamThread.java:686) ~[kafka-streams-3.7.1.jar:na] 	at org.apache.kafka.streams.processor.internals.StreamThread.run(StreamThread.java:645) ~[kafka-streams-3.7.1.jar:na] Caused by: com.google.protobuf.InvalidProtocolBufferException: Protocol message end-group tag did not match expected tag. 	at com.google.protobuf.InvalidProtocolBufferException.invalidEndTag(InvalidProtocolBufferException.java:114) ~[protobuf-java-3.25.5.jar:na] 	at com.google.protobuf.CodedInputStream$ArrayDecoder.checkLastTagWas(CodedInputStream.java:643) ~[protobuf-java-3.25.5.jar:na] 	at com.google.protobuf.AbstractParser.parsePartialFrom(AbstractParser.java:137) ~[protobuf-java-3.25.5.jar:na] 	at com.google.protobuf.AbstractParser.parseFrom(AbstractParser.java:168) ~[protobuf-java-3.25.5.jar:na] 	at com.google.protobuf.AbstractParser.parseFrom(AbstractParser.java:180) ~[protobuf-java-3.25.5.jar:na] 	at com.google.protobuf.AbstractParser.parseFrom(AbstractParser.java:185) ~[protobuf-java-3.25.5.jar:na] 	at com.google.protobuf.AbstractParser.parseFrom(AbstractParser.java:25) ~[protobuf-java-3.25.5.jar:na] 	at com.fx.market.kafka.message.FxRateEventProto.parseFrom(FxRateEventProto.java:283) ~[main/:na] 	at com.fx.market.kafka.FxRateEventProtoSerde$FxRateEventProtoDeserializer.deserialize(FxRateEventProtoSerde.java:31) ~[main/:na] 	... 13 common frames omitted
2024-12-31T12:56:50.144+02:00 ERROR 295771 --- [fxMarketDataProcessor] [-StreamThread-1] org.apache.kafka.streams.KafkaStreams    : stream-client [fx-market-processor-stream-operator-b643c2cc-d94a-409f-84ef-1e290420f6e7] Encountered the following exception during processing and the registered exception handler opted to SHUTDOWN_CLIENT. The streams client is going to shut down now.

org.apache.kafka.streams.errors.StreamsException: Deserialization exception handler is set to fail upon a deserialization error. If you would rather have the streaming pipeline continue after a deserialization error, please set the default.deserialization.exception.handler appropriately.
	at org.apache.kafka.streams.processor.internals.RecordDeserializer.deserialize(RecordDeserializer.java:86) ~[kafka-streams-3.7.1.jar:na]
	at org.apache.kafka.streams.processor.internals.RecordQueue.updateHead(RecordQueue.java:204) ~[kafka-streams-3.7.1.jar:na]
	at org.apache.kafka.streams.processor.internals.RecordQueue.addRawRecords(RecordQueue.java:128) ~[kafka-streams-3.7.1.jar:na]
	at org.apache.kafka.streams.processor.internals.PartitionGroup.addRawRecords(PartitionGroup.java:285) ~[kafka-streams-3.7.1.jar:na]
	at org.apache.kafka.streams.processor.internals.StreamTask.addRecords(StreamTask.java:1039) ~[kafka-streams-3.7.1.jar:na]
	at org.apache.kafka.streams.processor.internals.TaskManager.addRecordsToTasks(TaskManager.java:1782) ~[kafka-streams-3.7.1.jar:na]
	at org.apache.kafka.streams.processor.internals.StreamThread.pollPhase(StreamThread.java:1208) ~[kafka-streams-3.7.1.jar:na]
	at org.apache.kafka.streams.processor.internals.StreamThread.runOnceWithoutProcessingThreads(StreamThread.java:909) ~[kafka-streams-3.7.1.jar:na]
	at org.apache.kafka.streams.processor.internals.StreamThread.runLoop(StreamThread.java:686) ~[kafka-streams-3.7.1.jar:na]
	at org.apache.kafka.streams.processor.internals.StreamThread.run(StreamThread.java:645) ~[kafka-streams-3.7.1.jar:na]
Caused by: java.lang.RuntimeException: Failed to deserialize Protobuf message
	at com.fx.market.kafka.FxRateEventProtoSerde$FxRateEventProtoDeserializer.deserialize(FxRateEventProtoSerde.java:33) ~[main/:na]
	at com.fx.market.kafka.FxRateEventProtoSerde$FxRateEventProtoDeserializer.deserialize(FxRateEventProtoSerde.java:27) ~[main/:na]
	at org.apache.kafka.common.serialization.Deserializer.deserialize(Deserializer.java:62) ~[kafka-clients-3.7.1.jar:na]
	at org.apache.kafka.streams.processor.internals.SourceNode.deserializeValue(SourceNode.java:58) ~[kafka-streams-3.7.1.jar:na]
	at org.apache.kafka.streams.processor.internals.RecordDeserializer.deserialize(RecordDeserializer.java:66) ~[kafka-streams-3.7.1.jar:na]
	... 9 common frames omitted
Caused by: com.google.protobuf.InvalidProtocolBufferException: Protocol message end-group tag did not match expected tag.
	at com.google.protobuf.InvalidProtocolBufferException.invalidEndTag(InvalidProtocolBufferException.java:114) ~[protobuf-java-3.25.5.jar:na]
	at com.google.protobuf.CodedInputStream$ArrayDecoder.checkLastTagWas(CodedInputStream.java:643) ~[protobuf-java-3.25.5.jar:na]
	at com.google.protobuf.AbstractParser.parsePartialFrom(AbstractParser.java:137) ~[protobuf-java-3.25.5.jar:na]
	at com.google.protobuf.AbstractParser.parseFrom(AbstractParser.java:168) ~[protobuf-java-3.25.5.jar:na]
	at com.google.protobuf.AbstractParser.parseFrom(AbstractParser.java:180) ~[protobuf-java-3.25.5.jar:na]
	at com.google.protobuf.AbstractParser.parseFrom(AbstractParser.java:185) ~[protobuf-java-3.25.5.jar:na]
	at com.google.protobuf.AbstractParser.parseFrom(AbstractParser.java:25) ~[protobuf-java-3.25.5.jar:na]
	at com.fx.market.kafka.message.FxRateEventProto.parseFrom(FxRateEventProto.java:283) ~[main/:na]
	at com.fx.market.kafka.FxRateEventProtoSerde$FxRateEventProtoDeserializer.deserialize(FxRateEventProtoSerde.java:31) ~[main/:na]
	... 13 common frames omitted